# Generated by Django 5.2 on 2025-04-22 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAuth', '0002_modeluserpermission_modeluserrole_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='modelUserPermission',
        ),
    ]
