# Generated by Django 5.2 on 2025-04-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAuth', '0003_delete_modeluserpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeluser',
            name='password',
            field=models.CharField(),
        ),
    ]
