# Generated by Django 5.2 on 2025-07-09 09:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='modelNotes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField()),
                ('text', models.TextField()),
                ('link', models.CharField(unique=True)),
                ('is_cipher', models.BooleanField(default=False)),
                ('open_for_all', models.BooleanField(default=False)),
                ('edit_everyone', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAuth.modeluser')),
            ],
        ),
    ]
