# Generated by Django 5.2 on 2025-07-09 09:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='modelAccounts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('login', models.CharField(unique=True)),
                ('is_login_cipher', models.BooleanField(default=False)),
                ('password', models.CharField()),
                ('another_secret', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAuth.modeluser')),
            ],
        ),
        migrations.CreateModel(
            name='modelAccountsDeleted',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('login', models.CharField(unique=True)),
                ('is_login_cipher', models.BooleanField(default=False)),
                ('password', models.CharField()),
                ('another_secret', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAuth.modeluser')),
            ],
        ),
    ]
